# Generated by Django 6.0.2 on 2026-02-13 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf_cnpj', models.CharField(db_index=True, max_length=18, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email'], name='orders_clie_email_b88daa_idx'), models.Index(fields=['cpf_cnpj'], name='orders_clie_cpf_cnp_0181e8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado'), ('SEPARADO', 'Separado'), ('ENVIADO', 'Enviado'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], db_index=True, default='PENDENTE', max_length=20)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='orders.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('status_anterior', models.CharField(max_length=20)),
                ('novo_status', models.CharField(max_length=20)),
                ('usuario', models.CharField(max_length=100)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_status', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=30, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_estoque', models.PositiveIntegerField()),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['sku'], name='orders_prod_sku_899940_idx'), models.Index(fields=['nome'], name='orders_prod_nome_db78f2_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='orders.order')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.produto')),
            ],
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['data_criacao'], name='orders_orde_data_cr_c26e42_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('pedido', 'produto')},
        ),
    ]
