# Generated by Django 6.0.2 on 2026-02-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_idempotency_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatushistory',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
